version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: django
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - webnet

 

  # nginx:
  #   build: ./compose/nginx
  #   image: nginx:latest
  #   container_name: "nginx_con"
  #   depends_on:
  #     - django
  #   volumes:
  #     - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./staticfiles:/static
  #     - ./media:/media
  #     - /etc/letsencrypt/live/www.hypercodestech.com/fullchain.pem:/etc/letsencrypt/live/www.hypercodestech.com/fullchain.pem:ro
  #     - /etc/letsencrypt/live/www.hypercodestech.com/privkey.pem:/etc/letsencrypt/live/www.hypercodestech.com/privkey.pem:ro
  #   ports:
  #     - "80:80"
  #     - 443:443
  #   networks:
  #     - webnet
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always  
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - webnet

volumes:
  mysql_data:

networks:
  webnet:
    driver: bridge